const blueTeam = [
  {
    name: "Cyclops",
    realName: "Scott Summers",
    powers: ["Optic Blast", "Energy Resistance"],
    teamRole: "Team Leader",
    imageURL: "",
    heightFeet: 6,
    heightInches: 3,
    weight: 195,
    eyeColor: "Blue",
    hairColor: "Brown",
  },
  {
    name: "Wolverine",
    realName: "James Logan",
    powers: [
      "Regenerative Healing",
      "Superhuman Senses, Agility, Stamina, and Strength",
      "Adamantium Claws",
    ],
    teamRole: "Brawler",
    imageURL: "",
    heightFeet: 5,
    heightInches: 3,
    weight: 300,
    eyeColor: "Brown",
    hairColor: "Brown",
  },
  {
    name: "Psylocke",
    realName: "Elizabeth Braddock",
    powers: ["Telekinesis", "Telepathy", "Precognition"],
    teamRole: "Assassin",
    imageURL: "",
    heightFeet: 6,
    heightInches: 0,
    weight: 155,
    eyeColor: "Violet",
    hairColor: "Purple",
  },
  {
    name: "Beast",
    realName: "Hank McCoy",
    powers: [
      "Superhuman Strength, Speed, Stamina, Durability, Agility, Dexterity, and Senses",
      "Genius-level Intellect",
      "Claws and Fangs",
    ],
    teamRole: "Utility",
    imageURL: "",
    heightFeet: 5,
    heightInches: 11,
    weight: 402,
    eyeColor: "Blue",
    hairColor: "Blue",
  },
  {
    name: "Rogue",
    realName: "Anna Marie",
    powers: ["Power Absorption", "Flight", "Strength"],
    teamRole: "Rescue",
    imageURL: "",
    heightFeet: 5,
    heightInches: 8,
    weight: 120,
    eyeColor: "Green",
    hairColor: "Auburn",
  },
  {
    name: "Gambit",
    realName: "Remy Lebeau",
    powers: ["Molecular Acceleration", "Static Interference", "Hypnotic Charm"],
    teamRole: "Support",
    imageURL: "",
    heightFeet: 6,
    heightInches: 1,
    weight: 179,
    eyeColor: "Black w/ Red Pupils",
    hairColor: "Brown",
  },
];
